# Generated by Django 3.2.5 on 2021-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Date of Entry')),
                ('Country', models.CharField(max_length=200)),
                ('Vendor', models.CharField(max_length=1000)),
                ('Part_number', models.CharField(max_length=100)),
                ('License_name', models.CharField(max_length=1000)),
                ('Metric', models.CharField(max_length=1000)),
                ('Currency', models.CharField(max_length=50)),
                ('Process_number', models.CharField(max_length=100)),
                ('GLobal_price_listprice_USD', models.BigIntegerField(max_length=200)),
                ('Discount_from_pricelist', models.IntegerField(max_length=200)),
                ('Final_price_USD', models.IntegerField(max_length=200)),
                ('Finalprice_of_Localcurrency', models.IntegerField(max_length=200)),
                ('Awarded', models.CharField(max_length=10)),
                ('Quantity', models.CharField(max_length=50)),
                ('Volume_of_Deal', models.CharField(max_length=200)),
            ],
        ),
    ]
