# Generated by Django 3.2.5 on 2021-07-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Awarded',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='Country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='Currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Discount_from_pricelist',
            field=models.BigIntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='Final_price_USD',
            field=models.BigIntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='Finalprice_of_Localcurrency',
            field=models.IntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='GLobal_price_listprice_USD',
            field=models.BigIntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='License_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Metric',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='Process_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='Quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Vendor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Volume_of_Deal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
