# Generated by Django 3.2.5 on 2021-07-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210713_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Finalprice_of_Localcurrency',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
