# Generated by Django 3.2.5 on 2021-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210713_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Metric',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
